spring:
  sleuth:
    enabled: false
    sampler:
      percentage: 1.0
  cloud:
    config:
      uri: http://user:12345678@localhost:8888
      fail-fast: true
    stream:
      kafka:
       binder:
        zkNodes: localhost:2181
        brokers: localhost:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:12345678@localhost:8761/eureka/
  healthcheck:
    enabled: true
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 20
management:
  security:
    enabled: false
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      host: localhost:9200
      cluster: elasticsearch
      index: zipkin
      index-shards: 1
      index-replicas: 1
