spring:
  cloud:
    config:
      uri: http://user:12345678@localhost:8888
      fail-fast: true
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:12345678@localhost:8761/eureka/
  healthcheck:
    enabled: true
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 20
management:
  security:
    enabled: false
